version: "3"

services:

  redis:
    image: redis
    ports:
      - "6379:6379"

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    tty: true
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - .:/running
    depends_on:
      db:
        condition: service_healthy

  celery:
    build: .
    tty: true
    command: bash -c "celery -A config worker -l INFO"
    env_file:
      - .env
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    tty: true
    command: bash -c "celery -A config beat -l INFO -S django"
    env_file:
      - .env
    depends_on:
      - redis
      - app

volumes:
  pg_data: