# Generated by Django 5.0.6 on 2024-06-07 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_amount', models.CharField(blank=True, null=True, verbose_name='Цена платежа')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='Ссылка на оплату')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор платежа')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons.course', verbose_name='Название продукта')),
            ],
            options={
                'verbose_name': 'Оплата курса',
                'verbose_name_plural': 'Оплата курсов',
            },
        ),
    ]
